CREATE TABLE IF NOT EXISTS user (
	id INT PRIMARY KEY,
	full_name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	balance DECIMAL NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS email_index
ON user (email);
